llm:
  provider: "ollama"
  model_id: "mistral"
  base_url: "http://localhost:11434"

prompt_paths:
  generate_code: prompts/generate_code.j2
  fix_code_error: prompts/fix_code_error.j2
  review_commit: prompts/review_commit.j2