llm:
  provider: "claude"
  model_id: "anthropic.claude-3-sonnet-20240229"
  region: "us-east-1"
  temperature: 0.7
  max_tokens: 1024
  system_prompt: "You are a helpful assistant."

prompt_paths:
  generate_code: prompts/generate_code.j2
  fix_code_error: prompts/fix_code_error.j2
  review_commit: prompts/review_commit.j2